const ORDER_BY_RATING = 'ORDER_BY_RATING';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const ASCENDING = 'ASCENDING';
const DESCENDING = 'DESCENDING';
const FILTER_LOCAL = 'FILTER_LOCAL';
const FILTER_API = 'FILTER_API';
const LOADING = 'LOADING';
const GET_START = 'GET_START';
const GET_END = 'GET_END';
const POST_START = 'POST_START';
const POST_END = 'POST_END';
const NEXT = 'NEXT';


export {
  ORDER_BY_NAME,
  ORDER_BY_RATING,
  ASCENDING,
  DESCENDING,
  FILTER_LOCAL,
  FILTER_API,
  LOADING,
  GET_START,
  GET_END,
  POST_START,
  POST_END,
  NEXT,
};
