const ORDER_BY_RATING = 'ORDER_BY_RATING';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const ASCENDING = 'ASCENDING';
const DESCENDING = 'DESCENDING';
const FILTER_LOCAL = 'FILTER_LOCAL';
const FILTER_API = 'FILTER_API';
const FILTER_BY = 'FILTER_BY';
const GET_START = 'GET_START';
const GET_END = 'GET_END';
const GET_DETAILS = 'GET_DETAILS';
const DETAILS_START = 'DETAILS_START';
const POST_START = 'POST_START';
const POST_END = 'POST_END';
const PRELOAD = 'PRELOAD';
const FULL_PRELOAD = 'FULL_PRELOAD';
const NEXT = 'NEXT';
const FROM = 'FROM';
const GET_PLATFORMS = 'GET_PLATFORMS';
const GET_GENRES = 'GET_GENRES';
const RESET = 'RESET';
const FIND_BY_NAME = 'FIND_BY_NAME';


export {
  ORDER_BY_NAME,
  ORDER_BY_RATING,
  ASCENDING,
  DESCENDING,
  FILTER_BY,
  FILTER_LOCAL,
  FILTER_API,
  GET_START,
  GET_END,
  GET_DETAILS,
  DETAILS_START,
  POST_START,
  POST_END,
  PRELOAD,
  FULL_PRELOAD,
  NEXT,
  FROM,
  GET_PLATFORMS,
  GET_GENRES,
  RESET,
  FIND_BY_NAME,
};
